services:
  db:
    image: ankane/pgvector
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGUSER: ${DB_USER:-postgres}
      PGPASSWORD: ${DB_USER:-postgres}
      PGDATABASE: ${DB_NAME:-postgres}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  db-client:
    image: postgres:14-alpine
    command: tail -f /dev/null
    environment:
      PGUSER: ${DB_USER:-postgres}
      PGPASSWORD: ${DB_PASSWORD:-password}
      PGDATABASE: ${DB_NAME:-postgres}
      PGHOST: ${DB_HOST:-db}
      PGPORT: ${DB_PORT:-5432}
  sqlpad:
    image: sqlpad/sqlpad:7
    platform: linux/amd64
    hostname: "sqlpad"
    container_name: sqlpad
    ports:
      - "3001:3001"
    environment:
      SQLPAD_PORT: 3001
      SQLPAD_CONNECTIONS__demo__name: demo
      SQLPAD_CONNECTIONS__demo__driver: postgres
      SQLPAD_CONNECTIONS__demo__host: ${DB_HOST:-db}
      SQLPAD_CONNECTIONS__demo__port: ${DB_PORT:-5433}
      SQLPAD_CONNECTIONS__demo__username: ${DB_USER:-postgres}
      SQLPAD_CONNECTIONS__demo__password: ${DB_PASSWORD:-password}
      SQLPAD_CONNECTIONS__demo__multiStatementTransactionEnabled: 'true'
      SQLPAD_CONNECTIONS__demo__idleTimeoutSeconds: 86400
      SQLPAD_AUTH_DISABLED_DEFAULT_ROLE: admin
      SQLPAD_AUTH_DISABLED: true
      SQLPAD_APP_LOG_LEVEL: info
      SQLPAD_WEB_LOG_LEVEL: warn
volumes:
  pgdata:
